unique_ids:
  assets:
    standard-page.html: 36JWY3HLQKATV54NFKASZ2OVAX7QGTLW
    theme.css: BGAWMSXS2YWRI6HOTJ77TSRL6KPTYZFT
  forms:
    Form1: FW6KGXQF3LOZLY4VXNU6YYCEJOPUIQSM
  modules: {}
  scripts: {}
  server_modules: {}
